% initializeBoard
% Creates BOARD, an object of type Board which has the default layout of
% the board in Ticket to Ride.

if ~exist('INITIALIZE_BOARD_M', 'var')

    INITIALIZE_BOARD_M = true;

    initializeRoutes;

    BOARD = Board(ATLANTA_TO_CHARLESTON, ...
                  ATLANTA_TO_MIAMI, ...
                  ATLANTA_TO_NASHVILLE, ...
                  ATLANTA_TO_NEW_ORLEANS_A, ...
                  ATLANTA_TO_NEW_ORLEANS_B, ...
                  ATLANTA_TO_RALEIGH_A, ...
                  ATLANTA_TO_RALEIGH_B, ...
                  BOSTON_TO_MONTREAL_A, ...
                  BOSTON_TO_MONTREAL_B, ...
                  BOSTON_TO_NEW_YORK_A, ...
                  BOSTON_TO_NEW_YORK_B, ...
                  CALGARY_TO_HELENA, ...
                  CALGARY_TO_SEATTLE, ...
                  CALGARY_TO_VANCOUVER, ...
                  CALGARY_TO_WINNIPEG, ...
                  CHARLESTON_TO_MIAMI, ...
                  CHARLESTON_TO_RALEIGH, ...
                  CHICAGO_TO_DULUTH, ...
                  CHICAGO_TO_OMAHA, ...
                  CHICAGO_TO_PITTSBURG_A, ...
                  CHICAGO_TO_PITTSBURG_B, ...
                  CHICAGO_TO_SAINT_LOUIS_A, ...
                  CHICAGO_TO_SAINT_LOUIS_B, ...
                  CHICAGO_TO_TORONTO, ...
                  DALLAS_TO_EL_PASO, ...
                  DALLAS_TO_HOUSTON_A, ...
                  DALLAS_TO_HOUSTON_B, ...
                  DALLAS_TO_LITTLE_ROCK, ...
                  DALLAS_TO_OKLAHOMA_CITY_A, ...
                  DALLAS_TO_OKLAHOMA_CITY_B, ...
                  DENVER_TO_HELENA, ...
                  DENVER_TO_KANSAS_CITY_A, ...
                  DENVER_TO_KANSAS_CITY_B, ...
                  DENVER_TO_OKLAHOMA_CITY, ...
                  DENVER_TO_OMAHA, ...
                  DENVER_TO_PHOENIX, ...
                  DENVER_TO_SALT_LAKE_CITY_A, ...
                  DENVER_TO_SALT_LAKE_CITY_B, ...
                  DENVER_TO_SANTA_FE, ...
                  DULUTH_TO_HELENA, ...
                  DULUTH_TO_OMAHA_A, ...
                  DULUTH_TO_OMAHA_B, ...
                  DULUTH_TO_SAULT_ST_MARIE, ...
                  DULUTH_TO_TORONTO, ...
                  DULUTH_TO_WINNIPEG, ...
                  EL_PASO_TO_HOUSTON, ...
                  EL_PASO_TO_LOS_ANGELES, ...
                  EL_PASO_TO_OKLAHOMA_CITY, ...
                  EL_PASO_TO_PHOENIX, ...
                  EL_PASO_TO_SANTA_FE, ...
                  HELENA_TO_OMAHA, ...
                  HELENA_TO_SALT_LAKE_CITY, ...
                  HELENA_TO_SEATTLE, ...
                  HELENA_TO_WINNIPEG, ...
                  HOUSTON_TO_NEW_ORLEANS, ...
                  KANSAS_CITY_TO_OKLAHOMA_CITY_A, ...
                  KANSAS_CITY_TO_OKLAHOMA_CITY_B, ...
                  KANSAS_CITY_TO_OMAHA_A, ...
                  KANSAS_CITY_TO_OMAHA_B, ...
                  KANSAS_CITY_TO_SAINT_LOUIS_A, ...
                  KANSAS_CITY_TO_SAINT_LOUIS_B, ...
                  LAS_VEGAS_TO_LOS_ANGELES, ...
                  LAS_VEGAS_TO_SALT_LAKE_CITY, ...
                  LOS_ANGELES_TO_PHOENIX, ...
                  LOS_ANGELES_TO_SAN_FRANCISCO_A, ...
                  LOS_ANGELES_TO_SAN_FRANCISCO_B, ...
                  LITTLE_ROCK_TO_NASHVILLE, ...
                  LITTLE_ROCK_TO_NEW_ORLEANS, ...
                  LITTLE_ROCK_TO_OKLAHOMA_CITY, ...
                  LITTLE_ROCK_TO_SAINT_LOUIS, ...
                  MIAMI_TO_NEW_ORLEANS, ...
                  MONTREAL_TO_NEW_YORK, ...
                  MONTREAL_TO_SAULT_ST_MARIE, ...
                  MONTREAL_TO_TORONTO, ...
                  NASHVILLE_TO_PITTSBURG, ...
                  NASHVILLE_TO_RALEIGH, ...
                  NASHVILLE_TO_SAINT_LOUIS, ...
                  NEW_YORK_TO_PITTSBURG_A, ...
                  NEW_YORK_TO_PITTSBURG_B, ...
                  NEW_YORK_TO_WASHINGTON_DC_A, ...
                  NEW_YORK_TO_WASHINGTON_DC_B, ...
                  OKLAHOMA_CITY_TO_SANTA_FE, ...
                  PHOENIX_TO_SANTA_FE, ...
                  PITTSBURG_TO_RALEIGH, ...
                  PITTSBURG_TO_SAINT_LOUIS, ...
                  PITTSBURG_TO_TORONTO, ...
                  PITTSBURG_TO_WASHINGTON_DC, ...
                  PORTLAND_TO_SALT_LAKE_CITY, ...
                  PORTLAND_TO_SAN_FRANCISCO_A, ...
                  PORTLAND_TO_SAN_FRANCISCO_B, ...
                  PORTLAND_TO_SEATTLE_A, ...
                  PORTLAND_TO_SEATTLE_B, ...
                  RALEIGH_TO_WASHINGTON_DC_A, ...
                  RALEIGH_TO_WASHINGTON_DC_B, ...
                  SALT_LAKE_CITY_TO_SAN_FRANCISCO_A, ...
                  SALT_LAKE_CITY_TO_SAN_FRANCISCO_B, ...
                  SAULT_ST_MARIE_TO_TORONTO, ...
                  SAULT_ST_MARIE_TO_WINNIPEG, ...
                  SEATTLE_TO_VANCOUVER_A, ...
                  SEATTLE_TO_VANCOUVER_B);

end